import { ContentCalendarItem } from '../types';

export interface DriveItem {
  id: string;
  name: string;
  mimeType: string;
  modifiedTime?: string;
  webViewLink?: string;
}

export interface GoogleCalendarEvent {
  id: string;
  summary: string;
  description?: string;
  start: { dateTime: string };
  end: { dateTime: string };
  htmlLink?: string;
}

export const TARGET_DRIVE_FOLDER_ID = '1H4ZFpqFpQf_hNkeEIY4xYz_9W9l6VSFB';
export const TARGET_DRIVE_FOLDER_URL = `https://drive.google.com/drive/folders/${TARGET_DRIVE_FOLDER_ID}`;

export const LOGOS_DRIVE_FOLDER_ID = '1sYwEbr26nS4oHJ44DZicJPyhDPUTMqEt';
export const LOGOS_DRIVE_FOLDER_URL = `https://drive.google.com/drive/folders/${LOGOS_DRIVE_FOLDER_ID}`;

export const CHARACTERS_DRIVE_FOLDER_ID = '1AOdLv6iBaVdCalem7WJ21uNsfwEO45bn';
export const CHARACTERS_DRIVE_FOLDER_URL = `https://drive.google.com/drive/folders/${CHARACTERS_DRIVE_FOLDER_ID}`;

// ---------------------- GOOGLE DRIVE ----------------------

export async function listDriveFiles(token: string, folderId: string = TARGET_DRIVE_FOLDER_ID): Promise<DriveItem[]> {
  // Query both files in folder and user files
  const query = folderId
    ? `'${folderId}' in parents and trashed = false`
    : 'trashed = false';

  const url = `https://www.googleapis.com/drive/v3/files?pageSize=25&fields=files(id,name,mimeType,modifiedTime,webViewLink)&q=${encodeURIComponent(
    query
  )}`;

  let res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  // Fallback to general files query if specific folder has permission nuances
  if (!res.ok && folderId) {
    const fallbackUrl = 'https://www.googleapis.com/drive/v3/files?pageSize=25&fields=files(id,name,mimeType,modifiedTime,webViewLink)&q=trashed = false';
    res = await fetch(fallbackUrl, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
  }

  if (!res.ok) {
    const errorText = await res.text();
    throw new Error(`Google Drive API error: ${res.status} ${errorText}`);
  }

  const data = await res.json();
  return data.files || [];
}

export async function readDriveDocumentContent(token: string, fileId: string, mimeType: string): Promise<string> {
  let url = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`;
  if (mimeType === 'application/vnd.google-apps.document') {
    url = `https://www.googleapis.com/drive/v3/files/${fileId}/export?mimeType=text/plain`;
  }

  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  if (!res.ok) {
    throw new Error(`Failed to read Drive document: ${res.status}`);
  }

  return await res.text();
}

export async function uploadGraphicToDrive(
  token: string,
  base64PngDataUrl: string,
  fileName: string,
  folderId: string = TARGET_DRIVE_FOLDER_ID
): Promise<{ id: string; webViewLink?: string }> {
  // Convert Data URL to binary blob
  const base64Data = base64PngDataUrl.split(',')[1];
  const binaryString = atob(base64Data);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  const blob = new Blob([bytes], { type: 'image/png' });

  const metadata: Record<string, unknown> = {
    name: fileName,
    mimeType: 'image/png',
    description: 'Generated by AEObility Autonomous Social Engine',
  };

  if (folderId) {
    metadata.parents = [folderId];
  }

  const form = new FormData();
  form.append('metadata', new Blob([JSON.stringify(metadata)], { type: 'application/json' }));
  form.append('file', blob);

  const res = await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
    },
    body: form,
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Drive upload failed: ${res.status} ${err}`);
  }

  return await res.json();
}

// ---------------------- GOOGLE SHEETS ----------------------

export const CALENDAR_SHEET_HEADERS = [
  'Item ID',
  'IA Node ID',
  'Channel',
  'Title',
  'First-Fold Hook',
  'Copy',
  'Overlay H1',
  'Creative Asset Link',
  'Scheduled Date',
  'Scheduled Time',
  'Status',
  'Gatekeeper Score',
  'Live URL',
];

export async function createSocialCalendarSpreadsheet(
  token: string,
  sheetTitle: string = 'AEObility Social Content Calendar & Approval Queue'
): Promise<{ spreadsheetId: string; spreadsheetUrl: string }> {
  const payload = {
    properties: {
      title: sheetTitle,
    },
    sheets: [
      {
        properties: {
          title: 'Content Calendar',
          gridProperties: {
            frozenRowCount: 1,
            columnCount: 15,
            rowCount: 100,
          },
        },
        data: [
          {
            startRow: 0,
            startColumn: 0,
            rowData: [
              {
                values: CALENDAR_SHEET_HEADERS.map((h) => ({
                  userEnteredValue: { stringValue: h },
                  userEnteredFormat: {
                    textFormat: { bold: true, foregroundColor: { red: 1, green: 1, blue: 1 } },
                    backgroundColor: { red: 0.05, green: 0.1, blue: 0.2 },
                  },
                })),
              },
            ],
          },
        ],
      },
    ],
  };

  const res = await fetch('https://sheets.googleapis.com/v4/spreadsheets', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Failed to create spreadsheet: ${res.status} ${err}`);
  }

  const data = await res.json();
  return {
    spreadsheetId: data.spreadsheetId,
    spreadsheetUrl: data.spreadsheetUrl,
  };
}

export async function appendRowToGoogleSheet(
  token: string,
  spreadsheetId: string,
  item: ContentCalendarItem
): Promise<void> {
  const row = [
    item.id,
    item.iaNodeId,
    item.channel.toUpperCase(),
    item.title,
    item.hook,
    item.copy,
    item.overlayText || '',
    item.creativeAssetLink || '',
    item.scheduledDate,
    item.scheduledTime,
    item.status,
    `${item.gatekeeperScore}%`,
    item.liveUrl || '',
  ];

  const range = 'Content Calendar!A:M';
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values/${range}:append?valueInputOption=USER_ENTERED`;

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      range,
      majorDimension: 'ROWS',
      values: [row],
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Failed to append row to Google Sheet: ${res.status} ${err}`);
  }
}

export async function readRowsFromGoogleSheet(
  token: string,
  spreadsheetId: string
): Promise<string[][]> {
  const range = 'Content Calendar!A2:M';
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values/${encodeURIComponent(range)}`;

  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Failed to read Google Sheet: ${res.status} ${err}`);
  }

  const data = await res.json();
  return data.values || [];
}

// ---------------------- GOOGLE CALENDAR ----------------------

export async function listGoogleCalendarEvents(token: string): Promise<GoogleCalendarEvent[]> {
  const now = new Date().toISOString();
  const url = `https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${encodeURIComponent(now)}&maxResults=25&singleEvents=true&orderBy=startTime`;

  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Calendar list failed: ${res.status} ${err}`);
  }

  const data = await res.json();
  return data.items || [];
}

export async function createGoogleCalendarPublishingEvent(
  token: string,
  item: ContentCalendarItem
): Promise<GoogleCalendarEvent> {
  const dateStr = item.scheduledDate;
  const timeStr = item.scheduledTime || '09:00';
  const startIso = `${dateStr}T${timeStr}:00`;

  // Duration 30 mins
  const startDate = new Date(startIso);
  const endDate = new Date(startDate.getTime() + 30 * 60000);

  const payload = {
    summary: `[AEObility Social] Dispatch ${item.channel.toUpperCase()}: ${item.title.slice(0, 40)}`,
    description: `Automated Social Media Engine Publishing Slot\n\nChannel: ${item.channel.toUpperCase()}\nStatus: ${item.status}\nGatekeeper Score: ${item.gatekeeperScore}%\nHook:\n${item.hook}\n\nFull Copy:\n${item.copy}\n\nCreative Asset: ${item.creativeAssetLink || 'None'}\nCanonical Ref: ${item.iaNodeId}`,
    start: {
      dateTime: startDate.toISOString(),
      timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    },
    end: {
      dateTime: endDate.toISOString(),
      timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    },
    reminders: {
      useDefault: false,
      overrides: [
        { method: 'popup', minutes: 15 },
        { method: 'email', minutes: 60 },
      ],
    },
  };

  const res = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Failed to schedule Calendar event: ${res.status} ${err}`);
  }

  return await res.json();
}
