import { IANode, DriveFolderInfo } from '../types';

export const CONFIGURED_DRIVE_FOLDERS: DriveFolderInfo[] = [
  {
    id: '1H4ZFpqFpQf_hNkeEIY4xYz_9W9l6VSFB',
    name: 'Knowledge Base (IA & SLM Documents)',
    url: 'https://drive.google.com/drive/folders/1H4ZFpqFpQf_hNkeEIY4xYz_9W9l6VSFB?usp=drive_link',
    description: 'Core grounded repository containing Information Architecture (IA), SLM entity matrices, UX Styleguide, and Brand Book.',
    badge: 'GROUNDING ROOT',
    accentColor: '#00E5FF',
  },
  {
    id: '1sYwEbr26nS4oHJ44DZicJPyhDPUTMqEt',
    name: 'Logos Folder (Brand Identity Assets)',
    url: 'https://drive.google.com/drive/folders/1sYwEbr26nS4oHJ44DZicJPyhDPUTMqEt?usp=drive_link',
    description: 'High-resolution SVG and PNG logos, brand marks, monograms, dark/light variations, and favicon assets for slide decks and social graphics.',
    badge: 'LOGOS & MARKS',
    accentColor: '#FF007A',
  },
  {
    id: '1AOdLv6iBaVdCalem7WJ21uNsfwEO45bn',
    name: 'Characters Folder (Pattern-Interrupt Cutouts)',
    url: 'https://drive.google.com/drive/folders/1AOdLv6iBaVdCalem7WJ21uNsfwEO45bn?usp=drive_link',
    description: 'Cutout avatars including AI Bill in suit & sunglasses, compliance characters, and expressive humorous feed pattern-interrupts.',
    badge: 'CHARACTERS & CUTOUTS',
    accentColor: '#F59E0B',
  },
];

export const BRAND_LOGO_PRESETS = [
  {
    id: 'delta_triangle',
    name: 'AEObility Delta Prism (Vector Mark)',
    color: '#00E5FF',
    folderId: '1sYwEbr26nS4oHJ44DZicJPyhDPUTMqEt',
    description: 'Geometric cyan delta triangle representing forward directional retrieval indexing.',
  },
  {
    id: 'monogram',
    name: 'AEO Monogram Hex (Neon Green)',
    color: '#00FF85',
    folderId: '1sYwEbr26nS4oHJ44DZicJPyhDPUTMqEt',
    description: 'Precision engineering hexagon with embedded AEO telemetry monogram.',
  },
  {
    id: 'blueprint_seal',
    name: 'Blueprint Technical Seal (Amber & Dark Steel)',
    color: '#F59E0B',
    folderId: '1sYwEbr26nS4oHJ44DZicJPyhDPUTMqEt',
    description: 'ISO-style architectural stamp for research whitepapers and slide carousels.',
  },
];

export const CHARACTER_CUTOUT_PRESETS = [
  {
    id: 'ai_bill_suit',
    name: 'AI Bill (Smug in Navy Suit & Sunglasses)',
    folderId: '1AOdLv6iBaVdCalem7WJ21uNsfwEO45bn',
    description: 'Proud/smug pattern-interrupt stopping feed scrolls with humorous contrast against dense technical RAG subjects.',
    calloutText: 'AI BILL: PROUD & COMPLIANT',
    suitColor: '#1E293B',
    tieColor: '#EF4444',
  },
  {
    id: 'ai_bill_compliance',
    name: 'AI Bill (Lead Compliance Auditor)',
    folderId: '1AOdLv6iBaVdCalem7WJ21uNsfwEO45bn',
    description: 'Formal blazer with checklist badge, signaling 100% Australian English and zero marketing buzzwords.',
    calloutText: 'AUDIT PASSED: ZERO FLUFF',
    suitColor: '#0E1726',
    tieColor: '#00E5FF',
  },
  {
    id: 'ai_bill_auditor',
    name: 'AI Bill (Vector Search Engineer)',
    folderId: '1AOdLv6iBaVdCalem7WJ21uNsfwEO45bn',
    description: 'High-entropy engineering persona with neon telemetry shades and terminal badge.',
    calloutText: 'KV CACHE OPTIMISED',
    suitColor: '#1A0C38',
    tieColor: '#00FF85',
  },
];

export const INITIAL_IA_NODES: IANode[] = [
  {
    id: 'node-pos-bias',
    title: 'Positional Bias in Retrieval-Augmented Generation (RAG)',
    canonicalUrl: 'https://aeobility.com.au/research/positional-bias-rag-retrieval',
    primaryKeyphrase: 'positional bias in retrieval',
    targetIntent: 'Informational / Technical Authority',
    coreEntities: [
      'Lost-in-the-Middle Phenomenon',
      'Reciprocal Rank Fusion (RRF)',
      'Vector Chunking',
      'Attention Attenuation',
    ],
    takeaways: [
      'LLM context windows disproportionately weigh tokens located in the initial 15% and final 10% of the retrieved context block.',
      'Information placed in the middle 70% suffers an attention drop of up to 43% in factual recall tests.',
      'Re-ranking retrieved chunks using contextual entity salience prevents critical technical caveats from being discarded during synthesis.',
      'AEO optimisation requires restructuring content headers to mirror synthetic query vector alignments.',
    ],
    suggestedMetric: 'Recall Drop: -43.2% [Middle Quintile]',
    dateAdded: '2026-09-18',
  },
  {
    id: 'node-entity-salience',
    title: 'Entity Salience & Knowledge Graph Extraction in Generative Search',
    canonicalUrl: 'https://aeobility.com.au/research/entity-salience-generative-answers',
    primaryKeyphrase: 'entity salience generative search',
    targetIntent: 'Commercial Investigation / AEO Engineering',
    coreEntities: [
      'Semantic Triplet Extraction',
      'Wikidata QID Resolution',
      'Named Entity Recognition (NER)',
      'Schema Graph Architecture',
    ],
    takeaways: [
      'Search engines parse generative answers by resolving subject-predicate-object semantic triplets before text generation starts.',
      'Unanchored claims without Wikidata or Schema.org WebPage canonical entity nodes fail confidence thresholds in generative answer engines.',
      'Explicit entity disambiguation reduces synthetic hallucination risk by 68% in industry benchmark queries.',
      'Nested JSON-LD graphs must connect author credentials directly to verifiable institutional entities.',
    ],
    suggestedMetric: 'Disambiguation Gain: +68.4% Confidence',
    dateAdded: '2026-09-24',
  },
  {
    id: 'node-context-distill',
    title: 'Context Distillation & Token Density for Lightweight SLMs',
    canonicalUrl: 'https://aeobility.com.au/research/context-distillation-slm-compression',
    primaryKeyphrase: 'context distillation small language models',
    targetIntent: 'Technical Deep-Dive',
    coreEntities: [
      'Small Language Models (SLMs)',
      'KV Cache Pruning',
      'Prompt Compression',
      'Semantic Information Density',
    ],
    takeaways: [
      'Fluffy marketing prose inflates KV cache memory overhead by 3.8x with zero marginal lift in answer synthesis.',
      'Token distillation algorithms penalise low-entropy sentences while preserving dense technical nomenclature.',
      'Writing with high semantic density ensures that SLMs deployed at edge nodes preserve your canonical citation.',
      'Australian engineering benchmarks demonstrate that active voice phrasing improves token efficiency by 27%.',
    ],
    suggestedMetric: 'Cache Overhead: -3.8x Redundant Tokens',
    dateAdded: '2026-10-01',
  },
  {
    id: 'node-zero-click',
    title: 'Zero-Click AI Search Impression Modeling & Perplexity Grounding',
    canonicalUrl: 'https://aeobility.com.au/research/zero-click-ai-search-impression-modeling',
    primaryKeyphrase: 'zero click generative engine optimization',
    targetIntent: 'Executive Strategy / Enterprise AEO',
    coreEntities: [
      'Generative Engine Optimization (GEO)',
      'Citation Frequency Factor',
      'Perplexity Grounding',
      'Brand Recall Attribution',
    ],
    takeaways: [
      'Over 64% of informational queries now terminate inside the AI synthesized preview without an organic outbound click.',
      'Measurement frameworks must shift from organic SERP click-through rate (CTR) to Generative Citation Share (GCS).',
      'Direct factual definitions structured in clean declarative sentences gain 3.4x higher citation weighting.',
      'Canonical backlink anchors in third-party knowledge bases heavily influence AI model training weights.',
    ],
    suggestedMetric: 'GCS Correlation: r = 0.82 With Market Share',
    dateAdded: '2026-10-04',
  },
  {
    id: 'node-semantic-drift',
    title: 'Semantic Drift & Vector Cluster Stability in Embedding Indexing',
    canonicalUrl: 'https://aeobility.com.au/research/semantic-drift-vector-clustering',
    primaryKeyphrase: 'semantic drift vector database stability',
    targetIntent: 'Data Architecture / Systems Engineering',
    coreEntities: [
      'Cosine Proximity',
      'HNSW Graph Indexing',
      'Dimensionality Reduction',
      'Embedding Drift',
    ],
    takeaways: [
      'Continual content updates can drift vector embeddings outside of their original cluster neighbourhoods.',
      'Monitoring HNSW graph stability prevents unexpected drops in retrieval relevance during vector searches.',
      'Centroid tracking across 768-dimension embeddings provides early warning of topical dilution.',
      'Regular re-clustering ensures enterprise knowledge bases retain their semantic topology over time.',
    ],
    suggestedMetric: 'Drift Threshold: Max 0.04 Delta Cosine',
    dateAdded: '2026-10-06',
  },
];

export const BRAND_STYLEGUIDE = {
  name: 'AEObility Brand Book & UX Styleguide',
  locale: 'en-AU (Australian English)',
  persona: 'Founder-led Authority / Technical Systems Architect',
  tone: 'Clear, authoritative, analytical, rigorous, zero hype, zero fluff',
  spellingRules: [
    'Always use Australian/British English: "optimisation" not "optimization"',
    'Use "analyse" not "analyze"',
    'Use "behaviour" not "behavior"',
    'Use "centre" not "center"',
    'Use "prioritise" not "prioritize"',
    'Use "modelling" not "modeling"',
    'Use "licence" (noun) / "license" (verb)',
  ],
  forbiddenBuzzwords: [
    'game-changing',
    'game changer',
    'unlock',
    'revolutionise',
    'revolutionize',
    'skyrocket',
    'supercharge',
    'secret sauce',
    'delve',
    'cutting-edge',
    'harness the power',
    'dive deep',
    'unleash',
    'disrupt',
    'silver bullet',
    'synergy',
    'paradigm shift',
  ],
  firstFoldRule: 'Primary takeaway or hook MUST land within the first 120 characters before "See more" truncation.',
  ctaRule: 'Single eyebrow CTA must be concise (2 to 4 words) leading to canonical URL.',
  visualAesthetic: 'Dark telemetry & Blueprint Notebook, Geist Mono stats badges, H1 headlines max 8-10 words, high contrast.',
  hookStrategies: {
    directValueHook: 'Direct Value & Outcome Hook (Slide 1): Specific numbers + concrete outcome (e.g. "$995 got one trade business clearer citations in two crawl cycles")',
    patternInterrupt: 'Humorous Visual Pattern-Interrupt: Uses a cutout of AI Bill looking proud/smug in a suit to stop social feed scrolling',
    actionHeaders: 'Action-Driven Slide Headers: Instructional problem-solving statements (e.g., "What AI facts needs first", "Build passages one clean block at a time")',
  },
  typographyRules: {
    fontFamily: 'Modern Geometric Sans-Serif (Inter / Geist)',
    hierarchy: 'Heavy bold headlines with light/regular body text',
    keywordHighlighting: 'Selective yellow/amber/neon green highlight pills for single anchor keywords (e.g., "trade business", "facts", "passages", "signals", "Blueprint")',
    footerAnchor: 'Consistent Slide 1 hook repeated across the bottom of every card in small uniform weight',
  },
  blueprintAesthetic: {
    background: 'Subtle light-gray graph/grid lines ("Notebook / Blueprint" style)',
    palette: 'High-contrast neutral base accented by bright yellow highlights (#F59E0B) and orange carousel progress pills',
    cardElements: 'Rounded tactile card corners, soft drop shadows, and active carousel dot indicators',
  },
};

export const HOOK_STYLE_PRESETS = [
  {
    id: 'hook-direct-value',
    name: 'Direct Value & Outcome Hook',
    slide1H1: '$995 got one trade business clearer citations in two crawl cycles',
    subheadBadge: 'ROI: 2 Crawl Cycles [Direct Lift]',
    highlightWord: 'trade business',
    description: 'Pairs specific dollar investments with concrete algorithmic outcomes to spark instant curiosity and credibility.',
    bodyText: 'How restructuring semantic entity passages resolved local citation omissions.',
    footerAnchor: '$995 got one trade business clearer citations in two crawl cycles',
  },
  {
    id: 'hook-rag-recall',
    name: 'The Mid-Context Decay Hook',
    slide1H1: 'Why your enterprise RAG drops 43% of facts in the middle',
    subheadBadge: 'Recall Decay: -43.2% Middle Quintile',
    highlightWord: 'drops 43%',
    description: 'Direct technical provocation exposing the Lost-in-the-Middle retrieval flaw.',
    bodyText: 'Attention heads attenuate rapidly outside the first 15% and final 10% of tokens.',
    footerAnchor: 'Why your enterprise RAG drops 43% of facts in the middle',
  },
  {
    id: 'hook-zero-click',
    name: 'Zero-Click Authority Blueprint',
    slide1H1: '64% of searchers never click: here is the citation Blueprint',
    subheadBadge: 'Citation Share: r = 0.82 Market Share',
    highlightWord: 'Blueprint',
    description: 'Executive strategy hook addressing AI Overviews and Perplexity searcher behavior.',
    bodyText: 'How declarative semantic triplets capture citation share without organic clicks.',
    footerAnchor: '64% of searchers never click: here is the citation Blueprint',
  },
  {
    id: 'hook-action-passages',
    name: 'Passage Architecture Hook',
    slide1H1: 'Build passages one clean block at a time for AI search',
    subheadBadge: 'Entropy Gain: +27.4% Density',
    highlightWord: 'clean block',
    description: 'Action-driven instructional header pulling the reader through a stepwise framework.',
    bodyText: 'Low-entropy sentences inflate KV cache overhead without adding answer value.',
    footerAnchor: 'Build passages one clean block at a time for AI search',
  },
];

export const CHANNEL_MATRIX = [
  {
    channel: 'linkedin',
    name: 'LinkedIn',
    format: 'Founder-led narrative (first person), 3-line hook, no hashtags in body, clean spacing',
    charLimit: 3000,
    hookLimit: 120,
    linkPlacement: 'First comment or concise closing anchor',
    toneSpec: 'Technical founder authority, peer-to-peer engineering mindset',
  },
  {
    channel: 'instagram',
    name: 'Instagram Carousel',
    format: '5-Slide Carousel: Slide 1 (Hook), Slide 2 (Problem), Slide 3 (Data), Slide 4 (Fix), Slide 5 (CTA)',
    charLimit: 2200,
    hookLimit: 100,
    linkPlacement: 'Link in bio / Stories sticker link',
    toneSpec: 'Visual telemetry cards, punchy H1 (<10 words), precision data badge',
  },
  {
    channel: 'facebook',
    name: 'Facebook Page',
    format: 'Practical explainer for business operators and decision makers, relatable analogy',
    charLimit: 2000,
    hookLimit: 120,
    linkPlacement: 'Direct post link preview',
    toneSpec: 'Accessible plain English without losing technical credibility',
  },
  {
    channel: 'youtube',
    name: 'YouTube Shorts',
    format: '45-second spoken script with clear bracketed visual cues [ON SCREEN: ...]',
    charLimit: 1000,
    hookLimit: 80,
    linkPlacement: 'Pinned comment + description link',
    toneSpec: 'Dynamic, fast pacing, punchy cadence, zero intro waffle',
  },
  {
    channel: 'gmb',
    name: 'Google Business Profile',
    format: 'Local authority update with clear button CTA (LEARN_MORE), max 1,500 characters',
    charLimit: 1500,
    hookLimit: 120,
    linkPlacement: 'Native Call-To-Action button',
    toneSpec: 'Direct enterprise authority, concise problem statement, clear call to action',
  },
];
